name: php-app

services:
  app:
    build: .
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db


 
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vscode
      MYSQL_DATABASE: bootcamp_development

volumes:
  mysql: